### ISSUE TITLE
Does not support PowerShell 7

### ISSUE THREAD

**Issue by leewisestamp** [dgoldman-msft/PSServicePrincipal#27]
In trying to follow your instructions, I received the follow error: `At this time AzureAD PowerShell module does not work on PowerShell Core. Please use PowerShell version 5 or 6 to create Registered Applications.`

**Comment by dgoldman-msft** [comment]
Hi Lee! Can you please tell me what version of PowerShell you are using? You can do this by running $PSVersionTable in your PowerShell session. Currently this runs on 5.1 due to the AzureAD module not being compatible with PowerShell core.

**Comment by leewisestamp** [comment]
@dgoldman-msft 7.0.0 fresh install. Keep up the good work.

![image](https://user-images.githubusercontent.com/11390801/87543749-e7463000-c6ad-11ea-83cb-9a0bafd90e0a.png)

**Comment by dgoldman-msft** [comment]
Yes sir, that is the issue. If you use Windows PowerShell for now you won't have any issues. As soon as AzureAD is PS Core compatible I will have it updated for everyone :) Thanks for the compliment!

**Comment by leewisestamp** [comment]
Might be worth noting the README. Take care.

**Comment by dgoldman-msft** [comment]
Yes sir, doing it now as we speak!
