### ISSUE TITLE
Ownership of ServicePrincipal

### ISSUE THREAD

**Issue by Jakke2440** [dgoldman-msft/PSServicePrincipal#31]
Hello could there maybe an option to create an owner (or multiple) for the ServicePrincipal?

BTW I love your work; saves me a ton of hour ;)

**Comment by dgoldman-msft** [comment]
Hey there! Thanks for the kind words :) This module already has that feature. Just run New-ServicePrincipalObject -CreateBatchObjects -NameFile c:\temp\YourDataFile.txt with the rest of the switches that you want and this will create all your batch service principals :)
